import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import styles from "../styles/Home.module.css";

import Grid from "@mui/material/Unstable_Grid2";
import { Card, CardContent, Avatar } from "@mui/material";

import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Your App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/daylaixe/favicon.png" />
      </Head>
      <main>
        <div className={styles.icon_home_center}>
          <Avatar
            sx={{ width: 300, height: 300 }}
            src="/daylaixe/512x512.png"
          />
        </div>

        <Grid container spacing={2}>
          <Link href="/daylaixe">
            <Grid>
              <Card className={styles.card} sx={{ minWidth: 275 }}>
                <CardContent>
                  <h2 className={inter.className}>
                    Học lái xe <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                    Find in-depth information about Next.js features
                    and&nbsp;API.
                  </p>
                </CardContent>
              </Card>
            </Grid>
          </Link>

          <Link href="/daylaixe">
            <Grid>
              <Card className={styles.card} sx={{ minWidth: 275 }}>
                <CardContent>
                  <h2 className={inter.className}>
                    Thời khóa biểu <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                    Find in-depth information about Next.js features
                    and&nbsp;API.
                  </p>
                </CardContent>
              </Card>
            </Grid>
          </Link>

          <Link href="/login">
            <Grid>
              <Card className={styles.card} sx={{ minWidth: 275 }}>
                <CardContent>
                  <h2 className={inter.className}>
                    Đăng nhập <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                    Find in-depth information about Next.js features
                    and&nbsp;API.
                  </p>
                </CardContent>
              </Card>
            </Grid>
          </Link>

          <Link href="/daylaixe">
            <Grid>
              <Card className={styles.card} sx={{ minWidth: 275 }}>
                <CardContent>
                  <h2 className={inter.className}>
                    Học lái xe <span>-&gt;</span>
                  </h2>
                  <p className={inter.className}>
                    Find in-depth information about Next.js features
                    and&nbsp;API.
                  </p>
                </CardContent>
              </Card>
            </Grid>
          </Link>
        </Grid>
      </main>
    </>
  );
}
